### PR TITLE
Gracefully handle the inability to spawn threads, take 2

### LINKED ISSUE #24: Recover from thread spawn failure
Thanks for making this library.  I'm using it as a dependency of Tide:
[`tide`](https://crates.io/crates/tide) -> [`async-std`](https://crates.io/crates/async-std) -> [`async-global-executor`](https://crates.io/crates/async-global-executor) -> `blocking`
I'm running an API server in a VM which has limitations on number of threads (Heroku).

When the `blocking` library tries to spawn a new thread and fails, it poisons an internal mutex.  Then all future calls into the threadpool immediately panic.

This behavior makes `blocking` fragile.  Every server that depends on it is fragile.  Thread pool limits are insiffucient protection.  VMs often have other processes running that consume threads: cron, backups, ssh, deployments, etc.  I need my API server to be resilient.  I need it to stay up after failing to allocate a thread.

<details>
<summary>log.txt</summary>

```
{
  "time_ns": 1646202723428289154,
  "time": "2022-03-02T06:32:03.428Z",
  "module": "log_panics",
  "level": "ERROR",
  "message": "thread 'async-global-executor-1' panicked at 'called `Result::unwrap()` on an
  `Err` value: Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }':
  /tmp/codon/tmp/cache/cargo/registry/src/github.com-1ecc6299db9ec823/
  blocking-1.1.0/src/lib.rs:239
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   6: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   7: blocking::Executor::grow_pool
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: std::thread::local::LocalKey<T>::with
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: async_task::raw::RawTask<F,T,S>::run
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: async_io::driver::block_on
  24: std::thread::local::LocalKey<T>::with
  25: async_global_executor::threading::thread_main_loop
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone
"}
{
  "time_ns": 1646202723428453843,
  "time": "2022-03-02T06:32:03.428Z",
  "module": "log_panics",
  "level": "ERROR",
  "message": "thread 'blocking-1130' panicked at 'called `Result::unwrap()` on an
  `Err` value: PoisonError { .. }':
   /tmp/codon/tmp/cache/cargo/registry/src/github.com-1ecc6299db9ec823/
   blocking-1.1.0/src/lib.rs:189
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   6: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   7: blocking::Executor::main_loop
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  11: start_thread
  12: clone
"}
{
  "time_ns": 1646202723430010940,
  "time": "2022-03-02T06:32:03.430Z",
  "module": "log_panics",
  "level": "ERROR",
  "message": "thread 'async-global-executor-1' panicked at 'called `Result::unwrap()` on an
  `Err` value: PoisonError { .. }':
   /tmp/codon/tmp/cache/cargo/registry/src/github.com-1ecc6299db9ec823/
   blocking-1.1.0/src/lib.rs:211
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   6: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   7: blocking::Executor::schedule
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: std::thread::local::LocalKey<T>::with
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: async_task::raw::RawTask<F,T,S>::run
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: async_io::driver::block_on
  24: std::thread::local::LocalKey<T>::with
  25: async_global_executor::threading::thread_main_loop
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone
"}
```

</details>

### PR DESCRIPTION
**Pull request by notgull**
#27 was getting stale, so I replaced it with this one. Closes #24.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -245,10 +245,19 @@ impl Executor {
...
                 .spawn(move || self.main_loop())
-                .unwrap();
+            {
+                // We were unable to spawn the thread, so we need to undo the state changes.
+                log::error!("Failed to spawn a blocking thread: {}", e);
+                inner.idle_count -= 1;
+                inner.thread_count -= 1;
+
+                // The current number of threads is likely to be the system's upper limit, so update
+                // thread_limit accordingly.
```
Comment (taiki-e) [inline src/lib.rs:261]: (I wonder what happens if the thread creation fails when the thread_count is 0...)

**Review by taiki-e — COMMENTED** [review]
LGTM, but I would like to also hear @smol-rs/admins' thoughts on this.

File: src/lib.rs (hunk 1 above)
Comment (notgull) [reply src/lib.rs:261]: Right now, the current strategy is to just not run whatever runnables are in the queue, and wait for `grow_pool` to be invoked again on the off chance that whatever resource exhaustion prevented us from spawning a thread in the first place isn't happening anymore. However, this could lead to deadlocks on constrained systems. Panicking is also an option, but that feels like it detracts from the entire point.

File: src/lib.rs [hunk 2]
```diff
@@ -245,10 +245,19 @@ impl Executor {
             let id = ID.fetch_add(1, Ordering::Relaxed);
```
Comment (fogti) [inline src/lib.rs:248]: I think we should panic here on wrap around, do we do that already?

File: src/lib.rs (hunk 1 above)
Comment (fogti) [reply src/lib.rs:261]: when is `thread_limit` increased again?

File: src/lib.rs (hunk 2 above)
Comment (notgull) [reply src/lib.rs:248]: Could you clarify why that would be desired behavior? For wrapping IDs to actually pose an issue, there would need to be that many threads used, and the worst thing that happens is that two threads have the same name.

Comment (fogti) [reply src/lib.rs:248]: ah ok, if nothing except the name depends on it, then it doesn't matter.

File: src/lib.rs (hunk 1 above)
Comment (notgull) [reply src/lib.rs:261]: `thread_limit` is first set at the start of the program to either a default of 500 or to a user-defined value. Then, if there is an error while spawning a thread, `thread_limit` is set to the current thread count. It is never increased.

**Comment by notgull** [comment]
@smol-rs/admins Any blockers to merging this?

File: Cargo.toml [hunk 3]
```diff
@@ -21,3 +21,4 @@ async-task = "4.0.2"
 atomic-waker = "1.0.0"
 fastrand = "1.3.4"
 futures-lite = "1.11.0"
+log = "0.4.17"
```
Comment (fogti) [inline Cargo.toml:24]: this added non-optional dependency is probably not a good idea

File: src/lib.rs (hunk 1 above)
Comment (fogti) [reply src/lib.rs:261]: Can we ensure that `thread_limit` never drops to 0?

File: Cargo.toml (hunk 3 above)
Comment (notgull) [reply Cargo.toml:24]: `log` already appears in `smol`'s dependency tree several times, so I don't think it's unjustified to add it here. In addition, I think that reporting the error emitted by the thread spawn failure is probably better than just ignoring it.

Comment (fogti) [reply Cargo.toml:24]: I think `tracing` would maybe be a bit more appropriate, it is pretty widespread in the async ecosystem...

Comment (notgull) [reply Cargo.toml:24]: I can replace it here if you want, but if we do this I think we should go ahead and update [`async-io`](https://github.com/smol-rs/async-io/blob/f9ba3f7f8a9263ad173cdd734e31e4003e57af59/Cargo.toml#L25) and [`polling`](https://github.com/smol-rs/polling/blob/bc56d1fb380aec713473049b130c28e2835c3a9f/Cargo.toml#L26) with `tracing` as well.

File: src/lib.rs (hunk 1 above)
Comment (notgull) [reply src/lib.rs:261]: I've changed it so that, if it is about to be set to zero, it is set to one instead. I still don't think panicking is appropriate here.

File: Cargo.toml (hunk 3 above)
Comment (fogti) [reply Cargo.toml:24]: ok, we can do that later (e.g. if we do breaking-change releases of such crates)

File: src/lib.rs (hunk 1 above)
Comment (fogti) [reply src/lib.rs:261]: ok.

File: Cargo.toml (hunk 3 above)
Comment (notgull) [reply Cargo.toml:24]: I don't think this would be a breaking change, since the logging is entirely internal to the crates.

Comment (fogti) [reply Cargo.toml:24]: hmm idk.

**Review by fogti — APPROVED** [review]
